server:
  port: 8088

spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://127.0.0.1:3306/mistletoe-test
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true